name: clases2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  persistent_bottom_nav_bar: any
  flutter:
    sdk: flutter
  http: ^1.2.2
  google_fonts: ^6.2.1
  animated_text_kit: ^4.2.2
  crypto: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - data/productos.json
    - data/usuarios.json
